### ISSUE TITLE
v2 Latest update broken

### ISSUE THREAD

**Issue by dovry** [Spawnova/ShinsOverlayClass#11]
![image](https://github.com/Spawnova/ShinsOverlayClass/assets/15201298/ec9991c7-ae0f-4743-aede-d36278404511)

**Comment by Spawnova** [comment]
Sorry, I fixed that last night but hadn't yet pushed out the update, it's live now though so it should be fixed
this new version should fix the white screen issue that some people have

**Comment by dovry** [comment]
![image](https://github.com/Spawnova/ShinsOverlayClass/assets/15201298/0cde1d70-5501-448e-87bb-ea13c19d7f51)

**Comment by Spawnova** [comment]
Oh I see, I don't personally use ahk v2 so sometimes I forget the syntax, it doesn't use string in v2, so I'll remove the quotes and update, thank you

**Comment by dovry** [comment]
I fixed it by adding `*`as a param in the function

```
ShinsOverlayClass_OnErase(*) {
	return 0
}
```

https://old.reddit.com/r/AutoHotkey/comments/10nm6z8/hotkey_causing_invalid_callback_function_error/j69t5uz/

**Comment by Spawnova** [comment]
Perfect, I'll include that into the fix, thanks for letting me know =P
