### ISSUE TITLE
The overlay become white area

### ISSUE THREAD

**Issue by nminhdangit** [Spawnova/ShinsOverlayClass#5]
![image](https://user-images.githubusercontent.com/44900230/232190906-c827e5a0-f52f-4965-8737-5c4aab576d11.png)
When i comeback from sleep mode, the overlay area is become white. Can we fix this one ?

**Comment by Spawnova** [comment]
I've seen this behavior myself a few times, I will look into the issue soon and see if I can figure out how to solve it

**Comment by nminhdangit** [comment]
Okay. Hope you comeback soon

**Comment by Spawnova** [comment]
Yes, I have found a way to replicate the issue but the cause eludes me at the moment, time is hard to come by currently so progress is slow =[
