### ISSUE TITLE
DrawRectangle doesnt draw properly

### ISSUE THREAD

**Issue by KRN-8** [Spawnova/ShinsOverlayClass#7]
when using DrawRectangle with default thickness 1, the TopLeft pixel doesnt get drawn
with thickness 5, TR and BL are missing 1 pixel, TL is missing 3 (rounded too) and BottomRight is sharp corner

as a matter of fact, most thicknesses are by 1 pixel in radius:
 - smaller in TopLeft corner
 - bigger in BottomRight corner

also negative Width or and Height doesnt affect these directions ;-)

**Comment by Spawnova** [comment]
negative values are not supported for these functions

I see the problem with the missing pixel though, I will have a fix for it soon

**Comment by Spawnova** [comment]
Ah I see, my class does not support negative values but the direct2d function must handle it internally, the pixel issue will be fixed soon

**Comment by KRN-8** [comment]
not in a hurry, i just let u know ;-)

(also there is another issue but i need to figure out how to reproduce it before posting soo u dont get soo much work on your plate)
